### ISSUE TITLE
Error: password authentication failed for user

### ISSUE THREAD

**Issue by ParkerRex** [bmdavis419/weights-ai#1]
![SCR-20240425-itck](https://github.com/bmdavis419/weights-ai/assets/20405449/86063837-8f49-4f66-bdab-e27448f7a58d)

Hey Ben, 

Followed you on YT for a minute. Running your weights-ai project locally and keep running into this issue.

Whats going right
- I'm creating user in SB (stack im familiar with)
- Swapped out dbcredentials in `drizzle.config.ts`
- Clerk keys set

Curious what you think is going wrong.

I'd add a label as question because this isn't a bug - likely a config setup.

Also - curious how you're running the OAI calls, I see an OAI env var passed in config.toml and a reference to supabase.

**Comment by bmdavis419** [comment]
I'll have a full setup video pretty soon, changing a lot as we speak!

**Comment by bmdavis419** [comment]
Also as a note: I'm gonna do away with password auth all together. I really don't like it and just want oauth providers only
