### ISSUE TITLE
Question: Supabase migrations vs Drizzle migrations

### ISSUE THREAD

**Issue by trevorpfiz** [bmdavis419/weights-ai#2]
Hey Ben!

Just want to hear about your experience with handling migrations in this project, and what your workflow looks like when it comes to local dev/branching. 

I am seeing that Drizzle migrations do not work as smoothly with branching yet? https://twitter.com/plushdohn/status/1780126181490135371?

Have you changed the way you have been doing things since this tweet? https://twitter.com/bmdavis419/status/1762608689158979705

Thanks!

**Comment by bmdavis419** [comment]
Yea I've been doing it that way, but all of the migrations are already generated and committed for this project so u can just use those to work with it locally

As for the workflow the key scripts are "db:generate" and "db:generate:types"
